<a href="https://colab.research.google.com/github/tatadivine/DeepLearning_AI/blob/Master/loss_or_cost_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# Implement Mean Absolute Error

In [3]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [4]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

Implement same thing using numpy in much easier way

In [5]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [6]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [7]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))
mae_np(y_predicted, y_true)

np.float64(0.5)

Implement Log Loss or Binary Cross Entropy

In [8]:
np.log([0])

/tmp/ipykernel_740/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [9]:
epsilon = 1e-15
np.log([1e-15])

array([-34.53877639])

In [10]:
y_predicted

array([1, 1, 0, 0, 1])

In [11]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [12]:
1-epsilon

0.999999999999999

In [13]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [14]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [15]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [16]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

# Implement Mean Squared Error Function In Python

Solution 1: Without using numpy

In [17]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [18]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [19]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


np.float64(0.366)

Solution 2: By using numpy

In [20]:
np.mean(np.square(y_true-y_predicted))

np.float64(0.366)